users = 100
spawn-rate = 10
run-time = 3m
headless = true
locustfile = ./scenarios/http/gateway/existing_user_get_documents/scenario.py
html = ./scenarios/http/gateway/existing_user_get_documents/report.html
