users = 100
spawn-rate = 10
run-time = 3m
headless = true
locustfile = ./scenarios/grpc/gateway/new_user_issue_physical_card/scenario.py
html = ./scenarios/grpc/gateway/new_user_issue_physical_card/report.html
